### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Bach42b** [Bach42b/protospace-32402A#1]
自身のProtoSpaceのURL http://localhost:3000/

本番環境(Heroku)のURL  https://protospace-32402.herokuapp.com/

**Comment by kohei-ito** [comment]
Bach42b さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所が1点ございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
①コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう
　→現状、画像のようなエラーが出てしまいます
<img width="644" alt="スクリーンショット 2021-03-22 19 01 43" src="https://user-images.githubusercontent.com/65219321/111973197-97bfda00-8b41-11eb-81da-5cdbb1bf76ec.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Bach42b** [comment]
修正完了しました。
確認をお願い致します。

**Comment by Bach42b** [comment]
修正完了しました。
確認をお願い致します。

**Comment by tashu1211** [comment]
Bach42bさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
